In [2]:
import pandas as pd
import os

In [16]:
full_df = pd.read_csv(os.path.join('..', 'dataframe.csv'))
full_df.head()

,timestamp,position_lat,position_long,distance,time_from_course,speed,compressed_speed_distance,heart_rate,enhanced_altitude,altitude,enhanced_speed,power,grade,cadence,resistance,cycle_length,temperature,training
0,2024-02-29T16:05:27+00:00,-11.640456,166.994119,NaN,NaN,34.2324,NaN,85,13.2,13.2,34.2324,87,NaN,66,NaN,NaN,NaN,.\data\json\2024-02-29-17-04-33.fit.json
1,2024-02-29T16:05:28+00:00,-11.640510,166.994054,NaN,NaN,33.8076,NaN,85,13.2,13.2,33.8076,85,NaN,66,NaN,NaN,NaN,.\data\json\2024-02-29-17-04-33.fit.json
2,2024-02-29T16:05:29+00:00,-11.640566,166.993990,NaN,NaN,33.3900,NaN,85,13.2,13.2,33.3900,76,NaN,66,NaN,NaN,NaN,.\data\json\2024-02-29-17-04-33.fit.json
3,2024-02-29T16:05:30+00:00,-11.640625,166.993936,NaN,NaN,32.9292,NaN,86,13.2,13.2,32.9292,77,NaN,25,NaN,NaN,NaN,.\data\json\2024-02-29-17-04-33.fit.json
4,2024-02-29T16:05:31+00:00,-11.640685,166.993883,NaN,NaN,32.5296,NaN,86,13.2,13.2,32.5296,76,NaN,35,NaN,NaN,NaN,.\data\json\2024-02-29-17-04-33.fit.json

In [15]:
full_df.describe()

,position_lat,position_long,distance,time_from_course,speed,compressed_speed_distance,heart_rate,enhanced_altitude,altitude,enhanced_speed,power,grade,cadence,resistance,cycle_length,temperature
count,14663.000000,14663.000000,0.0,0.0,14663.000000,0.0,14663.000000,14663.000000,14663.000000,14663.000000,14663.000000,0.0,14663.000000,0.0,0.0,0.0
mean,1.930600,131.914304,NaN,NaN,27.231555,NaN,158.236991,20.566351,20.566351,27.231555,123.568369,NaN,64.253836,NaN,NaN,NaN
std,26.732554,68.989173,NaN,NaN,8.512839,NaN,16.730517,22.946025,22.946025,8.512839,61.644786,NaN,19.720775,NaN,NaN,NaN
min,-11.663637,-5.244547,NaN,NaN,0.000000,NaN,0.000000,-6.400000,-6.400000,0.000000,0.000000,NaN,0.000000,NaN,NaN,NaN
25%,-11.649099,166.937610,NaN,NaN,22.626000,NaN,154.000000,10.400000,10.400000,22.626000,95.000000,NaN,66.000000,NaN,NaN,NaN
50%,-11.642100,166.949100,NaN,NaN,28.731600,NaN,163.000000,13.200000,13.200000,28.731600,121.000000,NaN,70.000000,NaN,NaN,NaN
75%,-11.636711,166.982392,NaN,NaN,32.400000,NaN,169.000000,24.000000,24.000000,32.400000,150.000000,NaN,73.000000,NaN,NaN,NaN
max,55.659018,167.002798,NaN,NaN,58.521600,NaN,185.000000,131.800000,131.800000,58.521600,582.000000,NaN,116.000000,NaN,NaN,NaN

In [7]:
columns_with_all_nan = full_df.columns[full_df.isna().all()]
print(columns_with_all_nan)

Index(['distance', 'time_from_course', 'compressed_speed_distance', 'grade',
       'resistance', 'cycle_length', 'temperature'],
      dtype='object')

In [14]:
full_df.groupby('training').mean()

,position_lat,position_long,distance,time_from_course,speed,compressed_speed_distance,heart_rate,enhanced_altitude,altitude,enhanced_speed,power,grade,cadence,resistance,cycle_length,temperature
training,,,,,,,,,,,,,,,,
.\data\json\2024-02-29-17-04-33.fit.json,-11.641780,166.992516,NaN,NaN,24.444794,NaN,98.485294,13.200000,13.200000,24.444794,46.691176,NaN,37.352941,NaN,NaN,NaN
.\data\json\2024-02-29-17-10-41.fit.json,-11.640313,166.984394,NaN,NaN,28.714829,NaN,126.079268,13.532927,13.532927,28.714829,106.737805,NaN,56.853659,NaN,NaN,NaN
.\data\json\2024-02-29-17-19-52.fit.json,-11.658161,166.985415,NaN,NaN,26.286923,NaN,137.230769,13.504315,13.504315,26.286923,100.716698,NaN,62.497186,NaN,NaN,NaN
.\data\json\2024-02-29-19-29-20.fit.json,-11.646042,166.951352,NaN,NaN,26.008700,NaN,157.447510,4.153689,4.153689,26.008700,112.002999,NaN,59.811638,NaN,NaN,NaN
.\data\json\2024-03-03-19-36-49.fit.json,-11.646398,166.988959,NaN,NaN,29.901755,NaN,158.679237,13.688106,13.688106,29.901755,126.041442,NaN,66.213842,NaN,NaN,NaN
.\data\json\2024-03-04-20-10-27.fit.json,55.647399,-5.233761,NaN,NaN,26.625911,NaN,164.452632,36.778764,36.778764,26.625911,129.997254,NaN,67.411442,NaN,NaN,NaN
.\data\json\2024-03-06-17-47-43.fit.json,-11.643968,166.941293,NaN,NaN,23.876859,NaN,161.384049,37.812492,37.812492,23.876859,124.693786,NaN,61.792441,NaN,NaN,NaN
.\data\json\2024-03-06-18-49-22.fit.json,51.504332,-0.133296,NaN,NaN,28.444321,NaN,157.000000,18.116505,18.116505,28.444321,116.013350,NaN,60.128641,NaN,NaN,NaN
.\data\json\2024-03-09-16-50-26.fit.json,-11.645545,166.969868,NaN,NaN,29.087375,NaN,157.801736,10.294494,10.294494,29.087375,129.574451,NaN,67.193653,NaN,NaN,NaN